import Head from 'next/head'
import styled from 'styled-components';
import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';
import MainContent from './main';




const Home = () => {
    return (
          <>
            {/* <img id="shape_top" src="https://lukaszadam.com/assets/images/shape_top.svg" alt="free illustration shape"></img> */}
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
          <main>
            <Header/>
            {/* <MainContent/> */}
            {/* <Spacing>
                <h3>Recent blog posts.</h3>
            </Spacing> */}
            <Footer/>
          </main>
          </>
      );
}

const Spacing = styled.div`
  letter-spacing: 0.9px;
`;

const Bwrapper = styled.div`
  margin-top: 50px;
  
`;
const Container = styled.div`
  width: 100%;
  min-height: 100vh;
  padding-left: 25%;
  padding-right: 20%;
  box-sizing: border-box;
  overflow: hidden;
`;


        
        
export default Home;
      
