import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Nav from './components/Nav'
import MainContent from './components/Main'
import { AiFillGithub,AiOutlineTwitter,AiFillLinkedin } from 'react-icons/ai';
import TextLink from './components/TextLink/TextLink';
import Paragraph from './components/Paragraph/Paragraph';
import styled from 'styled-components';
import Underline from './components/Underline/Underline';
import Footer from './components/Footer/Footer';
import { BREAKPOINTS } from './constants';



export default function Home(){
  return (
    <>
     <Nav/>
    
    <div className="{styles.container}">
    <Head>
        <title>NaveenSingh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
        <span className="underline">Arya Stark</span>
        <TextLink href="#">
                Testingh
        </TextLink>
       
        <div className='banner-right'>
            <div className="nameintro">
                <div>Hello! I'm 
                    {/* <span className="myNameTitle"> AryaStark ✨</span> */}
                    <Title>Naveensingh</Title>
                </div>
                
                <p>
                    Front End Developer
                </p>
                
                <ul className='socialmedia-navigation flex'>
                    <li><AiOutlineTwitter size={28} /> </li>
                    <li><AiFillGithub size={28} /> </li>
                    <li><AiFillLinkedin size={28} /></li>
                </ul>
            <div>
        </div>
        </div>
        <img src='/assets/images/banner_test.png' width={500}/>
    </div>
      {/* Latest Post or Blog will be Listed Here */}
    <div>
        <div className='aboutcontent'>
            <h2>Latest Posts</h2>
            <hr/>
            <h3 className='blogheading'>Effective Collaboration with Product and Design</h3>
            <span>January 21st, 2020</span>


            <Paragraph>
            How we work with design can have a tremendous impact on our overall productivity, and yet we don't always treat it as very important. A look at how collaborating with design can supercharge our own productivity.
            </Paragraph>

            <h3 className='blogheading'>A gentle introduction to Framer Motion</h3>
            <span> January 18.05.2022</span>
            <Paragraph>
            How we work with design can have a tremendous impact on our overall productivity, and yet we don't always treat it as very important. A look at how collaborating with design can supercharge our own productivity.
            </Paragraph>
            <h3 className='blogheading'>Magical Rainbow Gradients with CSS Houdini and React Hooks</h3>
            <span> March 18.05.2022</span>
            <Paragraph>
            How we work with design can have a tremendous impact on our overall productivity, and yet we don't always treat it as very important. A look at how collaborating with design can supercharge our own productivity.
            </Paragraph>
            <h3 className="blogheading">My experience as a remote worker</h3>
            <span>April 18.05.2022</span>
            <Paragraph>
            How we work with design can have a tremendous impact on our overall productivity, and yet we don't always treat it as very important. A look at how collaborating with design can supercharge our own productivity.
            </Paragraph>
            <h3 className='blogheading'>Blog 5</h3>
            <span>Novemember 18.05.2022</span>
            <Paragraph>
            How we work with design can have a tremendous impact on our overall productivity, and yet we don't always treat it as very important. A look at how collaborating with design can supercharge our own productivity.
            </Paragraph>
            {/* <h3>Blog 6</h3>
            <span>18.05.2022</span>
            <Paragraph>
            How we work with design can have a tremendous impact on our overall productivity, and yet we don't always treat it as very important. A look at how collaborating with design can supercharge our own productivity.
            </Paragraph>
            <Underline>
                ff
            </Underline> */}
        </div>
    </div>
    </main>
</div>

    {/* <footer>
            <p>All that stuff up there was written by me,</p>
    </footer> */}
    <Footer>

    </Footer>
</>
);

}

const Title = styled.h1`
  margin-bottom: 48px;
  font-size: 3.4rem;
  font-weight: 900;
  letter-spacing: -2.4px;

  @media ${BREAKPOINTS.sm} {
    font-size: 3.5rem;
    letter-spacing: -1px;
  }
`;
